### ISSUE TITLE
Answer option buttons still make tapping sound when their x-scale is zero

### ISSUE THREAD

**Issue by Daniel-Ian-Robinson** [NyoomNyoom/COSC345-Manu-project#14]
To replicate, answer a question and tap submit. When two or three of the options go away (the animation that reduces their x-scale from one to zero), tap on the space where they used to be and you will hear the usual button tapping sound.

It must be because they still exist in the layout. This is not a big issue, but should be ironed out by beta.

Commit hash: c90b1a88397b53d5f3ec0983fd7b2a19d164a2b5

**Comment by NyoomNyoom** [comment]
@Daniel-Ian-Robinson could you "hide" the buttons or remove them from the view when they hit zero?

**Comment by Daniel-Ian-Robinson** [comment]
From Trello: "You can tap buttons after the answer has been revealed. We may want to remove this by making the buttons unclickable in this state. This would also fix the problem of the tapping sound playing when you tap the answers that disappear."
