### ISSUE TITLE
Quiz: if you click the 'X' button twice within 0.5 seconds, it opens the "Return to Menu?" popup twice.

### ISSUE THREAD

**Issue by Daniel-Ian-Robinson** [NyoomNyoom/COSC345-Manu-project#30]
Commit hash ID: 4ab4740cd69068d19b287df7db2f3e62d369abaf

**Comment by Daniel-Ian-Robinson** [comment]
Likely because the background of the popup is transparent and it lets you click through it momentarily.

**Comment by NyoomNyoom** [comment]
fixed on commit [c3ee4166b2290e47425e982d93febb04551f6a9b](https://github.com/NyoomNyoom/COSC345-Manu-project/commit/c3ee4166b2290e47425e982d93febb04551f6a9bl)
