### ISSUE TITLE
Some bird names too big for button

### ISSUE THREAD

**Issue by Daniel-Ian-Robinson** [NyoomNyoom/COSC345-Manu-project#31]
Some bird names, such as the Oystercatcher, are too long to fit on one line of the button. They make the button higher to fit (since the button's height is set to "wrap_content"). This moves the other view elements around because the parent LinearLayout is centre-aligned vertically. This choppiness between questions looks a bit off and should be fixed before beta.

Commit hash ID: f1169557938c171b3c429c0cb3395a49c1b10f05

**Comment by NyoomNyoom** [comment]
Make the buttons larger (IE double the size of the buttons now). This will mean that the smaller bird names will still be centered and the larger names will still look normal. This also stops the buttons from jumping around on screen and changing sizes. You will have to hard code the size of the buttons.
